apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: family
spec:
  selector:
    matchLabels:
      app:  frontend
  template:
    metadata:
      labels:
        app:  frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - frontend
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - name:  frontend
        image: luke19/familyfrontend:<VERSION>
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: 1000m
          requests:
            memory: 256Mi
            cpu: 150m
        ports:
        - containerPort: 8080 #Expose containerport to the pod
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: family-config
              key: REACT_APP_API_URL
        livenessProbe: #Check that pod is ready
          httpGet:
            path: / #path to check
            port: 8080
          initialDelaySeconds: 10 #start checking after 30 seconds
          periodSeconds: 10 #check every 30 seconds
          failureThreshold: 10
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          exec:
            command:
            - cat
            - /etc/nginx/nginx.conf