apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: family
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  frontend
  template:
    metadata:
      labels:
        app:  frontend
    spec:
      initContainers:
      - name: wait-for-apiservice
        image: stefanevinance/wait-for-200
        imagePullPolicy: IfNotPresent
        env:
          - name: TIMEOUT
            value: '5'
          - name: URL
            value: http://apiservice.family:8080/swagger-ui.html
      containers:
      - name:  frontend
        image: luke19/familyfrontend:<VERSION>
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: 1000m
          requests:
            memory: 256Mi
            cpu: 150m
        ports:
        - containerPort: 8080 #Expose containerport to the pod
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: family-config
              key: REACT_APP_API_URL
        livenessProbe: #Check that pod is ready
          httpGet:
            path: / #path to check
            port: 8080
          initialDelaySeconds: 10 #start checking after 30 seconds
          periodSeconds: 10 #check every 30 seconds
          failureThreshold: 10
        readinessProbe: #Check that pod is healthy
          httpGet:
            path: / #path to check
            port: 8080 #port to check
          initialDelaySeconds: 15 #start checking after 15 seconds
          periodSeconds: 10 #check every 3 seconds
          failureThreshold: 10
