// tslint:disable
/// <reference path="./custom.d.ts" />
/**
 * Auth Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as url from "url";
import { Configuration } from "./configuration";
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';

const BASE_PATH = "http://localhost/api".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *  
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError" = "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface AllowedApplication
 */
export interface AllowedApplication {
    /**
     * 
     * @type {string}
     * @memberof AllowedApplication
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AllowedApplication
     */
    appname?: string;
    /**
     * 
     * @type {string}
     * @memberof AllowedApplication
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof AllowedApplication
     */
    cssClasses?: string;
}

/**
 * 
 * @export
 * @interface Authentication
 */
export interface Authentication {
    /**
     * 
     * @type {string}
     * @memberof Authentication
     */
    token: string;
    /**
     * 
     * @type {Array<AllowedApplication>}
     * @memberof Authentication
     */
    allowedApplicationList?: Array<AllowedApplication>;
}

/**
 * 
 * @export
 * @interface Changed
 */
export interface Changed {
    /**
     * 
     * @type {boolean}
     * @memberof Changed
     */
    changed?: boolean;
}

/**
 * 
 * @export
 * @interface JWTToken
 */
export interface JWTToken {
    /**
     * 
     * @type {string}
     * @memberof JWTToken
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof JWTToken
     */
    jwt?: string;
}

/**
 * 
 * @export
 * @interface Login
 */
export interface Login {
    /**
     * 
     * @type {string}
     * @memberof Login
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof Login
     */
    password: string;
}

/**
 * 
 * @export
 * @interface MFATokenVerification
 */
export interface MFATokenVerification {
    /**
     * 
     * @type {string}
     * @memberof MFATokenVerification
     */
    mfaToken: string;
    /**
     * 
     * @type {string}
     * @memberof MFATokenVerification
     */
    username?: string;
}

/**
 * 
 * @export
 * @interface Password
 */
export interface Password {
    /**
     * 
     * @type {string}
     * @memberof Password
     */
    password: string;
}

/**
 * 
 * @export
 * @interface QRCode
 */
export interface QRCode {
    /**
     * 
     * @type {string}
     * @memberof QRCode
     */
    qrcode?: string;
}

/**
 * 
 * @export
 * @interface Resetted
 */
export interface Resetted {
    /**
     * 
     * @type {boolean}
     * @memberof Resetted
     */
    resetted: boolean;
}

/**
 * 
 * @export
 * @interface TokenVerifiyResponse
 */
export interface TokenVerifiyResponse {
    /**
     * 
     * @type {boolean}
     * @memberof TokenVerifiyResponse
     */
    mfaNeeded?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TokenVerifiyResponse
     */
    mfaAction?: TokenVerifiyResponse.MfaActionEnum;
}

/**
 * @export
 * @namespace TokenVerifiyResponse
 */
export declare namespace TokenVerifiyResponse {
    /**
     * @export
     * @enum {string}
     */
    export enum MfaActionEnum {
        Setup = 'setup',
        Verifiy = 'verifiy'
    }
}

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username?: string;
}

/**
 * 
 * @export
 * @interface Verified
 */
export interface Verified {
    /**
     * 
     * @type {string}
     * @memberof Verified
     */
    verificationMessage: string;
}


/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Authenticate a customer
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticate(xRequestID: string, xRealIP: string, login: Login, options: any = {}): RequestArgs {
            // verify required parameter 'xRequestID' is not null or undefined
            if (xRequestID === null || xRequestID === undefined) {
                throw new RequiredError('xRequestID','Required parameter xRequestID was null or undefined when calling authenticate.');
            }
            // verify required parameter 'xRealIP' is not null or undefined
            if (xRealIP === null || xRealIP === undefined) {
                throw new RequiredError('xRealIP','Required parameter xRealIP was null or undefined when calling authenticate.');
            }
            // verify required parameter 'login' is not null or undefined
            if (login === null || login === undefined) {
                throw new RequiredError('login','Required parameter login was null or undefined when calling authenticate.');
            }
            const localVarPath = `/auth`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xRequestID !== undefined && xRequestID !== null) {
                localVarHeaderParameter['X-Request-ID'] = String(xRequestID);
            }

            if (xRealIP !== undefined && xRealIP !== null) {
                localVarHeaderParameter['X-Real-IP'] = String(xRealIP);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"Login" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(login || {}) : (login || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Change the User Password
         * @param {string} username the name of the user
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {Password} password 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(username: string, JWT: string, xRequestID: string, xRealIP: string, password: Password, options: any = {}): RequestArgs {
            // verify required parameter 'username' is not null or undefined
            if (username === null || username === undefined) {
                throw new RequiredError('username','Required parameter username was null or undefined when calling changePassword.');
            }
            // verify required parameter 'JWT' is not null or undefined
            if (JWT === null || JWT === undefined) {
                throw new RequiredError('JWT','Required parameter JWT was null or undefined when calling changePassword.');
            }
            // verify required parameter 'xRequestID' is not null or undefined
            if (xRequestID === null || xRequestID === undefined) {
                throw new RequiredError('xRequestID','Required parameter xRequestID was null or undefined when calling changePassword.');
            }
            // verify required parameter 'xRealIP' is not null or undefined
            if (xRealIP === null || xRealIP === undefined) {
                throw new RequiredError('xRealIP','Required parameter xRealIP was null or undefined when calling changePassword.');
            }
            // verify required parameter 'password' is not null or undefined
            if (password === null || password === undefined) {
                throw new RequiredError('password','Required parameter password was null or undefined when calling changePassword.');
            }
            const localVarPath = `/auth/{username}`
                .replace(`{${"username"}}`, encodeURIComponent(String(username)));
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (JWT !== undefined && JWT !== null) {
                localVarHeaderParameter['JWT'] = String(JWT);
            }

            if (xRequestID !== undefined && xRequestID !== null) {
                localVarHeaderParameter['X-Request-ID'] = String(xRequestID);
            }

            if (xRealIP !== undefined && xRealIP !== null) {
                localVarHeaderParameter['X-Real-IP'] = String(xRealIP);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"Password" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(password || {}) : (password || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all users
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} sOURCXRealIPEIP 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers(JWT: string, xRequestID: string, sOURCXRealIPEIP: string, options: any = {}): RequestArgs {
            // verify required parameter 'JWT' is not null or undefined
            if (JWT === null || JWT === undefined) {
                throw new RequiredError('JWT','Required parameter JWT was null or undefined when calling getUsers.');
            }
            // verify required parameter 'xRequestID' is not null or undefined
            if (xRequestID === null || xRequestID === undefined) {
                throw new RequiredError('xRequestID','Required parameter xRequestID was null or undefined when calling getUsers.');
            }
            // verify required parameter 'sOURCXRealIPEIP' is not null or undefined
            if (sOURCXRealIPEIP === null || sOURCXRealIPEIP === undefined) {
                throw new RequiredError('sOURCXRealIPEIP','Required parameter sOURCXRealIPEIP was null or undefined when calling getUsers.');
            }
            const localVarPath = `/auth`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (JWT !== undefined && JWT !== null) {
                localVarHeaderParameter['JWT'] = String(JWT);
            }

            if (xRequestID !== undefined && xRequestID !== null) {
                localVarHeaderParameter['X-Request-ID'] = String(xRequestID);
            }

            if (sOURCXRealIPEIP !== undefined && sOURCXRealIPEIP !== null) {
                localVarHeaderParameter['SOURCX-Real-IPE_IP'] = String(sOURCXRealIPEIP);
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register a customer
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register(JWT: string, xRequestID: string, xRealIP: string, login: Login, options: any = {}): RequestArgs {
            // verify required parameter 'JWT' is not null or undefined
            if (JWT === null || JWT === undefined) {
                throw new RequiredError('JWT','Required parameter JWT was null or undefined when calling register.');
            }
            // verify required parameter 'xRequestID' is not null or undefined
            if (xRequestID === null || xRequestID === undefined) {
                throw new RequiredError('xRequestID','Required parameter xRequestID was null or undefined when calling register.');
            }
            // verify required parameter 'xRealIP' is not null or undefined
            if (xRealIP === null || xRealIP === undefined) {
                throw new RequiredError('xRealIP','Required parameter xRealIP was null or undefined when calling register.');
            }
            // verify required parameter 'login' is not null or undefined
            if (login === null || login === undefined) {
                throw new RequiredError('login','Required parameter login was null or undefined when calling register.');
            }
            const localVarPath = `/auth`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'PATCH' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (JWT !== undefined && JWT !== null) {
                localVarHeaderParameter['JWT'] = String(JWT);
            }

            if (xRequestID !== undefined && xRequestID !== null) {
                localVarHeaderParameter['X-Request-ID'] = String(xRequestID);
            }

            if (xRealIP !== undefined && xRealIP !== null) {
                localVarHeaderParameter['X-Real-IP'] = String(xRealIP);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"Login" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(login || {}) : (login || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reset the Counter for MFA
         * @param {string} username the name of the user
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {JWTToken} jWTToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetMfa(username: string, JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options: any = {}): RequestArgs {
            // verify required parameter 'username' is not null or undefined
            if (username === null || username === undefined) {
                throw new RequiredError('username','Required parameter username was null or undefined when calling resetMfa.');
            }
            // verify required parameter 'JWT' is not null or undefined
            if (JWT === null || JWT === undefined) {
                throw new RequiredError('JWT','Required parameter JWT was null or undefined when calling resetMfa.');
            }
            // verify required parameter 'xRequestID' is not null or undefined
            if (xRequestID === null || xRequestID === undefined) {
                throw new RequiredError('xRequestID','Required parameter xRequestID was null or undefined when calling resetMfa.');
            }
            // verify required parameter 'xRealIP' is not null or undefined
            if (xRealIP === null || xRealIP === undefined) {
                throw new RequiredError('xRealIP','Required parameter xRealIP was null or undefined when calling resetMfa.');
            }
            // verify required parameter 'jWTToken' is not null or undefined
            if (jWTToken === null || jWTToken === undefined) {
                throw new RequiredError('jWTToken','Required parameter jWTToken was null or undefined when calling resetMfa.');
            }
            const localVarPath = `/auth/{username}`
                .replace(`{${"username"}}`, encodeURIComponent(String(username)));
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (JWT !== undefined && JWT !== null) {
                localVarHeaderParameter['JWT'] = String(JWT);
            }

            if (xRequestID !== undefined && xRequestID !== null) {
                localVarHeaderParameter['X-Request-ID'] = String(xRequestID);
            }

            if (xRealIP !== undefined && xRealIP !== null) {
                localVarHeaderParameter['X-Real-IP'] = String(xRealIP);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"JWTToken" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(jWTToken || {}) : (jWTToken || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Verifiy the jwt
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {JWTToken} jWTToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyToken(JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options: any = {}): RequestArgs {
            // verify required parameter 'JWT' is not null or undefined
            if (JWT === null || JWT === undefined) {
                throw new RequiredError('JWT','Required parameter JWT was null or undefined when calling verifyToken.');
            }
            // verify required parameter 'xRequestID' is not null or undefined
            if (xRequestID === null || xRequestID === undefined) {
                throw new RequiredError('xRequestID','Required parameter xRequestID was null or undefined when calling verifyToken.');
            }
            // verify required parameter 'xRealIP' is not null or undefined
            if (xRealIP === null || xRealIP === undefined) {
                throw new RequiredError('xRealIP','Required parameter xRealIP was null or undefined when calling verifyToken.');
            }
            // verify required parameter 'jWTToken' is not null or undefined
            if (jWTToken === null || jWTToken === undefined) {
                throw new RequiredError('jWTToken','Required parameter jWTToken was null or undefined when calling verifyToken.');
            }
            const localVarPath = `/auth`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (JWT !== undefined && JWT !== null) {
                localVarHeaderParameter['JWT'] = String(JWT);
            }

            if (xRequestID !== undefined && xRequestID !== null) {
                localVarHeaderParameter['X-Request-ID'] = String(xRequestID);
            }

            if (xRealIP !== undefined && xRealIP !== null) {
                localVarHeaderParameter['X-Real-IP'] = String(xRealIP);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"JWTToken" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(jWTToken || {}) : (jWTToken || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Authenticate a customer
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticate(xRequestID: string, xRealIP: string, login: Login, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Authentication> {
            const localVarAxiosArgs = AuthApiAxiosParamCreator(configuration).authenticate(xRequestID, xRealIP, login, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = Object.assign(localVarAxiosArgs.options, {url: basePath + localVarAxiosArgs.url})
                return axios.request(axiosRequestArgs);                
            };
        },
        /**
         * 
         * @summary Change the User Password
         * @param {string} username the name of the user
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {Password} password 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(username: string, JWT: string, xRequestID: string, xRealIP: string, password: Password, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Changed> {
            const localVarAxiosArgs = AuthApiAxiosParamCreator(configuration).changePassword(username, JWT, xRequestID, xRealIP, password, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = Object.assign(localVarAxiosArgs.options, {url: basePath + localVarAxiosArgs.url})
                return axios.request(axiosRequestArgs);                
            };
        },
        /**
         * 
         * @summary Get all users
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} sOURCXRealIPEIP 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers(JWT: string, xRequestID: string, sOURCXRealIPEIP: string, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<User>> {
            const localVarAxiosArgs = AuthApiAxiosParamCreator(configuration).getUsers(JWT, xRequestID, sOURCXRealIPEIP, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = Object.assign(localVarAxiosArgs.options, {url: basePath + localVarAxiosArgs.url})
                return axios.request(axiosRequestArgs);                
            };
        },
        /**
         * 
         * @summary Register a customer
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register(JWT: string, xRequestID: string, xRealIP: string, login: Login, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<JWTToken> {
            const localVarAxiosArgs = AuthApiAxiosParamCreator(configuration).register(JWT, xRequestID, xRealIP, login, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = Object.assign(localVarAxiosArgs.options, {url: basePath + localVarAxiosArgs.url})
                return axios.request(axiosRequestArgs);                
            };
        },
        /**
         * 
         * @summary Reset the Counter for MFA
         * @param {string} username the name of the user
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {JWTToken} jWTToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetMfa(username: string, JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Resetted> {
            const localVarAxiosArgs = AuthApiAxiosParamCreator(configuration).resetMfa(username, JWT, xRequestID, xRealIP, jWTToken, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = Object.assign(localVarAxiosArgs.options, {url: basePath + localVarAxiosArgs.url})
                return axios.request(axiosRequestArgs);                
            };
        },
        /**
         * 
         * @summary Verifiy the jwt
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {JWTToken} jWTToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyToken(JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenVerifiyResponse> {
            const localVarAxiosArgs = AuthApiAxiosParamCreator(configuration).verifyToken(JWT, xRequestID, xRealIP, jWTToken, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = Object.assign(localVarAxiosArgs.options, {url: basePath + localVarAxiosArgs.url})
                return axios.request(axiosRequestArgs);                
            };
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Authenticate a customer
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticate(xRequestID: string, xRealIP: string, login: Login, options?: any) {
            return AuthApiFp(configuration).authenticate(xRequestID, xRealIP, login, options)(axios, basePath);
        },
        /**
         * 
         * @summary Change the User Password
         * @param {string} username the name of the user
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {Password} password 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(username: string, JWT: string, xRequestID: string, xRealIP: string, password: Password, options?: any) {
            return AuthApiFp(configuration).changePassword(username, JWT, xRequestID, xRealIP, password, options)(axios, basePath);
        },
        /**
         * 
         * @summary Get all users
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} sOURCXRealIPEIP 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers(JWT: string, xRequestID: string, sOURCXRealIPEIP: string, options?: any) {
            return AuthApiFp(configuration).getUsers(JWT, xRequestID, sOURCXRealIPEIP, options)(axios, basePath);
        },
        /**
         * 
         * @summary Register a customer
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register(JWT: string, xRequestID: string, xRealIP: string, login: Login, options?: any) {
            return AuthApiFp(configuration).register(JWT, xRequestID, xRealIP, login, options)(axios, basePath);
        },
        /**
         * 
         * @summary Reset the Counter for MFA
         * @param {string} username the name of the user
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {JWTToken} jWTToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetMfa(username: string, JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options?: any) {
            return AuthApiFp(configuration).resetMfa(username, JWT, xRequestID, xRealIP, jWTToken, options)(axios, basePath);
        },
        /**
         * 
         * @summary Verifiy the jwt
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {JWTToken} jWTToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyToken(JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options?: any) {
            return AuthApiFp(configuration).verifyToken(JWT, xRequestID, xRealIP, jWTToken, options)(axios, basePath);
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Authenticate a customer
     * @param {string} xRequestID 
     * @param {string} xRealIP 
     * @param {Login} login 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authenticate(xRequestID: string, xRealIP: string, login: Login, options?: any) {
        return AuthApiFp(this.configuration).authenticate(xRequestID, xRealIP, login, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @summary Change the User Password
     * @param {string} username the name of the user
     * @param {string} JWT 
     * @param {string} xRequestID 
     * @param {string} xRealIP 
     * @param {Password} password 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public changePassword(username: string, JWT: string, xRequestID: string, xRealIP: string, password: Password, options?: any) {
        return AuthApiFp(this.configuration).changePassword(username, JWT, xRequestID, xRealIP, password, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @summary Get all users
     * @param {string} JWT 
     * @param {string} xRequestID 
     * @param {string} sOURCXRealIPEIP 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public getUsers(JWT: string, xRequestID: string, sOURCXRealIPEIP: string, options?: any) {
        return AuthApiFp(this.configuration).getUsers(JWT, xRequestID, sOURCXRealIPEIP, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @summary Register a customer
     * @param {string} JWT 
     * @param {string} xRequestID 
     * @param {string} xRealIP 
     * @param {Login} login 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public register(JWT: string, xRequestID: string, xRealIP: string, login: Login, options?: any) {
        return AuthApiFp(this.configuration).register(JWT, xRequestID, xRealIP, login, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @summary Reset the Counter for MFA
     * @param {string} username the name of the user
     * @param {string} JWT 
     * @param {string} xRequestID 
     * @param {string} xRealIP 
     * @param {JWTToken} jWTToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public resetMfa(username: string, JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options?: any) {
        return AuthApiFp(this.configuration).resetMfa(username, JWT, xRequestID, xRealIP, jWTToken, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @summary Verifiy the jwt
     * @param {string} JWT 
     * @param {string} xRequestID 
     * @param {string} xRealIP 
     * @param {JWTToken} jWTToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public verifyToken(JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options?: any) {
        return AuthApiFp(this.configuration).verifyToken(JWT, xRequestID, xRealIP, jWTToken, options)(this.axios, this.basePath);
    }

}

/**
 * MfaApi - axios parameter creator
 * @export
 */
export const MfaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary setup mfa and receive the qrcode
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {JWTToken} jWTToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mfaSetup(JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options: any = {}): RequestArgs {
            // verify required parameter 'JWT' is not null or undefined
            if (JWT === null || JWT === undefined) {
                throw new RequiredError('JWT','Required parameter JWT was null or undefined when calling mfaSetup.');
            }
            // verify required parameter 'xRequestID' is not null or undefined
            if (xRequestID === null || xRequestID === undefined) {
                throw new RequiredError('xRequestID','Required parameter xRequestID was null or undefined when calling mfaSetup.');
            }
            // verify required parameter 'xRealIP' is not null or undefined
            if (xRealIP === null || xRealIP === undefined) {
                throw new RequiredError('xRealIP','Required parameter xRealIP was null or undefined when calling mfaSetup.');
            }
            // verify required parameter 'jWTToken' is not null or undefined
            if (jWTToken === null || jWTToken === undefined) {
                throw new RequiredError('jWTToken','Required parameter jWTToken was null or undefined when calling mfaSetup.');
            }
            const localVarPath = `/mfa/setup`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (JWT !== undefined && JWT !== null) {
                localVarHeaderParameter['JWT'] = String(JWT);
            }

            if (xRequestID !== undefined && xRequestID !== null) {
                localVarHeaderParameter['X-Request-ID'] = String(xRequestID);
            }

            if (xRealIP !== undefined && xRealIP !== null) {
                localVarHeaderParameter['X-Real-IP'] = String(xRealIP);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"JWTToken" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(jWTToken || {}) : (jWTToken || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary verify mfa
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {MFATokenVerification} mFATokenVerification 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mfaVerify(JWT: string, xRequestID: string, xRealIP: string, mFATokenVerification: MFATokenVerification, options: any = {}): RequestArgs {
            // verify required parameter 'JWT' is not null or undefined
            if (JWT === null || JWT === undefined) {
                throw new RequiredError('JWT','Required parameter JWT was null or undefined when calling mfaVerify.');
            }
            // verify required parameter 'xRequestID' is not null or undefined
            if (xRequestID === null || xRequestID === undefined) {
                throw new RequiredError('xRequestID','Required parameter xRequestID was null or undefined when calling mfaVerify.');
            }
            // verify required parameter 'xRealIP' is not null or undefined
            if (xRealIP === null || xRealIP === undefined) {
                throw new RequiredError('xRealIP','Required parameter xRealIP was null or undefined when calling mfaVerify.');
            }
            // verify required parameter 'mFATokenVerification' is not null or undefined
            if (mFATokenVerification === null || mFATokenVerification === undefined) {
                throw new RequiredError('mFATokenVerification','Required parameter mFATokenVerification was null or undefined when calling mfaVerify.');
            }
            const localVarPath = `/mfa/verify`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (JWT !== undefined && JWT !== null) {
                localVarHeaderParameter['JWT'] = String(JWT);
            }

            if (xRequestID !== undefined && xRequestID !== null) {
                localVarHeaderParameter['X-Request-ID'] = String(xRequestID);
            }

            if (xRealIP !== undefined && xRealIP !== null) {
                localVarHeaderParameter['X-Real-IP'] = String(xRealIP);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"MFATokenVerification" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(mFATokenVerification || {}) : (mFATokenVerification || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MfaApi - functional programming interface
 * @export
 */
export const MfaApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary setup mfa and receive the qrcode
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {JWTToken} jWTToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mfaSetup(JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<QRCode> {
            const localVarAxiosArgs = MfaApiAxiosParamCreator(configuration).mfaSetup(JWT, xRequestID, xRealIP, jWTToken, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = Object.assign(localVarAxiosArgs.options, {url: basePath + localVarAxiosArgs.url})
                return axios.request(axiosRequestArgs);                
            };
        },
        /**
         * 
         * @summary verify mfa
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {MFATokenVerification} mFATokenVerification 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mfaVerify(JWT: string, xRequestID: string, xRealIP: string, mFATokenVerification: MFATokenVerification, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Verified> {
            const localVarAxiosArgs = MfaApiAxiosParamCreator(configuration).mfaVerify(JWT, xRequestID, xRealIP, mFATokenVerification, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = Object.assign(localVarAxiosArgs.options, {url: basePath + localVarAxiosArgs.url})
                return axios.request(axiosRequestArgs);                
            };
        },
    }
};

/**
 * MfaApi - factory interface
 * @export
 */
export const MfaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary setup mfa and receive the qrcode
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {JWTToken} jWTToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mfaSetup(JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options?: any) {
            return MfaApiFp(configuration).mfaSetup(JWT, xRequestID, xRealIP, jWTToken, options)(axios, basePath);
        },
        /**
         * 
         * @summary verify mfa
         * @param {string} JWT 
         * @param {string} xRequestID 
         * @param {string} xRealIP 
         * @param {MFATokenVerification} mFATokenVerification 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mfaVerify(JWT: string, xRequestID: string, xRealIP: string, mFATokenVerification: MFATokenVerification, options?: any) {
            return MfaApiFp(configuration).mfaVerify(JWT, xRequestID, xRealIP, mFATokenVerification, options)(axios, basePath);
        },
    };
};

/**
 * MfaApi - object-oriented interface
 * @export
 * @class MfaApi
 * @extends {BaseAPI}
 */
export class MfaApi extends BaseAPI {
    /**
     * 
     * @summary setup mfa and receive the qrcode
     * @param {string} JWT 
     * @param {string} xRequestID 
     * @param {string} xRealIP 
     * @param {JWTToken} jWTToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MfaApi
     */
    public mfaSetup(JWT: string, xRequestID: string, xRealIP: string, jWTToken: JWTToken, options?: any) {
        return MfaApiFp(this.configuration).mfaSetup(JWT, xRequestID, xRealIP, jWTToken, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @summary verify mfa
     * @param {string} JWT 
     * @param {string} xRequestID 
     * @param {string} xRealIP 
     * @param {MFATokenVerification} mFATokenVerification 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MfaApi
     */
    public mfaVerify(JWT: string, xRequestID: string, xRealIP: string, mFATokenVerification: MFATokenVerification, options?: any) {
        return MfaApiFp(this.configuration).mfaVerify(JWT, xRequestID, xRealIP, mFATokenVerification, options)(this.axios, this.basePath);
    }

}

